name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.GH_TOKEN_V2 }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm ci

      - name: Publish Release
        run: npx semantic-release --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_V2 }}
